### PR TITLE
implement unboxing

### PR DESCRIPTION
**Pull request by Gozala**
Relates to #43

### CODE REVIEW

**Comment by mikaelbr** [comment]
Discussion at #43.

**Comment by Gozala** [comment]
@mikaelbr Yeah I just created this pull to illustrate what I was suggesting :) I was gonna mention that in issue we were discussing, just got distracted.

**Comment by mikaelbr** [comment]
Merged in fd5fa10c0dc38ed3ebe2516c5e23552ba337e278! Thanks for your help. Merged manually in as some changes were made, and didn't want the dist-file just yet.

**Comment by Gozala** [comment]
@mikaelbr can you please comment back once version with this change is published to npm, so I can update dependency from my fork to a version.

**Pull request closed without merging**
