### PR TITLE
make hiddenCursorField configurable with `cursorField` option and add test

### PR DESCRIPTION
**Pull request by phated**
ref https://github.com/omniscientjs/omniscient/issues/52#issuecomment-75108113

### CODE REVIEW

**Comment by torgeir** [comment]
That's kind of nifty, actually! Update the docs and we'll merge it.

**Comment by mikaelbr** [comment]
I've updated the docs here: https://omniscientjs.github.io/api/

**Comment by mikaelbr** [comment]
Neat implementation. I was somewhat unsure if this is an Public API layer we wanted (more defaults to override, the more public API to maintain etc), and it might cause surprises. But in the end, I think it's handy and would ease usage without ES2015 transpiler, and it would probably not be surprising as it's explicitly opt-in.

Thanks again.

**Comment by phated** [comment]
Thanks!  I really like the `withDefaults` API. It allows you to be prescriptive with the default export but expose the inner workings for people that need it.

**Comment by torgeir** [comment]
:+1:

**Pull request merged**
