### PR TITLE
Adds option for always using JSX

### PR DESCRIPTION
**Pull request by mikaelbr**
Following the discussion of #46 , this PR adds a option for always using JSX with Omniscient. This would make the usage much easier for the JSX folks.

### CODE REVIEW

**Comment by phated** [comment]
Awesome!

**Comment by phated** [comment]
I think the biggest downside to this is you don't get the implicit unboxing of your cursor and need to access it as `props.cursor` instead of `props`

**Comment by mikaelbr** [comment]
I get that, but again, when passing it in jsx you define the propery name yourself and it would be kind of a surprising behaviour if it some time unboxes if using a specific name, and other times not, or? I think maybe a better approach is to use es6 destructuring if you use jsx with harmony or 6to5.

**Comment by phated** [comment]
Sounds good.  I really like the behavior of non-jsx usage of omniscient.  I am a little concerned with `React.DOM` going away for `React.createElement` and making non-jsx usage look really bad.  I was looking to pair JSnoX with this library but the 2 different styles are jarring.  I'm also considering making `omniscient-dom` that is similar to `React.DOM` but implemented with the nicer API.  Sorry, just rambling.

**Comment by torgeir** [comment]
Hah! Why didn't we think of this. 

Yea, I agree, the destructuring part when passing named props is actually quite nice once you get used to it, also you don't have to care for the order of arguments which is nice

Ramble away! We enjoy good suggestions :) Also liking the nonjsx way, I've been thinking about going for an omniscient dom api myself. Was hoping es6 could help, but its actually even more work, as you can't destructure "for real" in the imports, so you need

```
import {DOM} from 'react/addons';
let {div} = DOM;
```

At least with jsx you only need to require react..

**Comment by dendril** [comment]
@mikaelbr When do you plan the release of this change? Because I been playing with `react-router` and I have to use the property `.jsx` to correctly connect `omniscient` with `react-router` (extracted from the examples provided by you).

Cheers!

**Comment by dendril** [comment]
Found the answer by myself => v3.0.0 :)

**Pull request merged**
